# Generated by Django 4.0.1 on 2022-01-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=100)),
                ('feedback_title', models.CharField(max_length=50)),
                ('feedback_topic', models.CharField(max_length=200)),
                ('feedback_date', models.DateField()),
            ],
        ),
    ]
